### ISSUE TITLE
Homework 03 is ready for grading

### ISSUE THREAD

**Issue by Shirlett** [Shirlett/STAT545-hw-Hall-Shirlett#2]

**Comment by yeonukkim** [comment]
### Peer review from Yeonuk:
I think this homework should get check plus.
#### 1. Criteria and results
- No obvious mistakes: Yes
- Pleasant to read: Yes
- Did more than 3 tasks: Yes
#### 2. What I learn
- My major difficulty for this homework was also layout. The package **gridExtra** which you used looks great and I eager to incorporate it into my future work.
- I did not choose *trim task*, so I didn’t know how to compute a trimmed mean before seeing your homework. It is really useful.
- Overall, your code looks concise and easy to understand. 
- The detailed reflection looks good.
#### 3. Suggestions
- Why don’t you try to include error ranges (or bars) in your 3rd and 4th plots? This can help people to see the changes in distribution over time.
- The 4th and 5th tables are too long to see. If you made columns representing each continent and rearranged the tables by year, it would be more readable.

**Comment by vmichalowski** [comment]
Hi @Shirlett 

Great work overall on your homework 3! I can tell you put a lot of thought into your coding and went the above what was expected for these tasks. 

Here are a few comments:
- Very detailed process report, which was great, because I found it really easy to follow your thought process and what you did to accomplish the tasks.
- For your task titled "Report the absolute and/or relative abundance of countries with low life expectancy over time by continent," a bar chart would have been more intuitive for me to understand the message of the charts, rather than using points. But I really like your idea to facet wrap by year, very organized and clear.
- I didn't find a way to put my plots and tables side by side, so I applaud your efforts to make that happen!
- Nice work for your "extra" task! It would be interesting to see how those 10 countries you identified as having the lowest life expectancy compared to the rest of the countries in Africa, to get an idea of how low they are relative to the rest of them too.

Cheers,
Victoria
