### ISSUE TITLE
HW06 is ready for grading

### ISSUE THREAD

**Issue by Shirlett** [Shirlett/STAT545-hw-Hall-Shirlett#6]
![HW06](https://github.com/Shirlett/STAT545-hw-Hall-Shirlett/tree/master/HW06)

**Comment by bcahn7** [comment]
Hello @Shirlett ,
Here are some comments on your hw06. Hope it helps!

- You have such a good reflection on your work.
- You have a well-organized understanding on string. I learned a lot of functions in `stringr`!
- I learned the difference among `paste()`, `paste0()`, and `str_c()`.
- It would be really useful in textual analysis to convert a vector of strings into a single string (make a function and use `str_c()`) and to convert a single string into a vector of strings (use `str_split()`)
- In `str_view()`, `^` and `$` would help to find the exact word. 

- In part 2, `ggplot` seems not to work because either of `library(ggplot2)` or `library(tidyverse)` was not declared explicitly.
- Codes are well-organized in `Bags of Joy or Bags of Despair to Trick or Treaters` and `What About the General Attitude of Specific Age Groups toward Mint Flavored Candy?`. Topics sound interesting and I was able to easily grasp the point with a `kable`.
- Good try with assessing the accuracy of the city name in the `singer` data. I learned how `stringdist()` can be used in this context. `city` in the `singer` contains **only city** name, **only state** name, or **city, state** name. So, it would be an alternative to see how many values are in each category. 
- I got exactly same troubles as yours in `revgeocode()` and Google Map API. I am glad to hear that you fixed all the troubles!

Overall, your answers are well-explained. I was able to understand even what I didn't choose for my assignment. You did a great job!

**Comment by yidie** [comment]
Hi @Shirlett,

- Character data
Good job working through the tutorial on strings! It would be better if you can write down some comments/explanations on how you solve those exercises. Good use of `stringr::words` in the exercises to do the matchings. Maybe try to write sentences/prompts outside of the r code chunks instead of constantly commenting out since you are using rmd, not the usual r script. And it would look nicer this way.

- Candy data
I am impressed by how you clean up the data. This is a very important step before actually analyzing the data. And you have comments which make it easy to understand what you are doing. Maybe you want to fix the `ggplot` issue as @bcahn7 suggested. Good use of 'gather()' to reshape the data and all the dplyr functions to manipulate the data. And you really came up with interesting questions and addressed them with nicely created tables and figures. I also appreciate that you interpret the results.

- Singer data
You wrote your own function that maps each row in the data frame. And you use `map2()` together with your `my_find()` function to add addresses in the data frame. good job! You explained what the output of `stringdist()` means in terms of how accurate a match is. Very impressed with what you did.

Overall, great work! Well organized homework. And the reflection is vey detailed and thorough. It clearly shows that you put a lot of efforts in this homework and learned a lot. Well done!

Yidie
