### ISSUE TITLE
HW07 ready for grading!

### ISSUE THREAD

**Issue by Shirlett** [Shirlett/STAT545-hw-Hall-Shirlett#7]
![HW07](https://github.com/Shirlett/STAT545-hw-Hall-Shirlett/tree/master/HW07)

**Comment by yanchaoluo** [comment]
Hi @Shirlett
 I am very happy to review your homework and it's a really nice job!
Here are my comments:

+ I download your repo and try to run Makefile. I do not know why it doesn't work on my computer and there is nothing showing up. 
![image](https://user-images.githubusercontent.com/31666422/32935192-dcf21f66-cb23-11e7-9629-166ea2fc2459.png)

+ In your part 1, you did all the requirements in the assignment such as clean the data rearrange factors, dropped variables etc. and I very like your choropleth map, it nice supports for your dot plot.

+ In your part 2,  you use many packages and after each package, there is a detailed explanation of what this package does. In addition, for each linear regression graph, you use P- value to indicate that the relationship between x-axis and y-axis is significant. Moreover, I also learn a useful function `grid.arrange`.

+ I have a tinny suggestion, maybe next time you could explain how your pipeline works, and try to add the dependency diagram by using this link: [the dependency diagram](https://github.com/lindenb/makefile2graph)

+ The overall structure of your report is clear and organized, and you use both "Makefile" and "master script in R" to automate the pipeline, that's great!
Overall, It is a nice assignment,  thank you for inviting me.

**Comment by Shirlett** [comment]
Thanks much. I should have mentioned that I tried to install the
make2filegraph but it seems to only work for Linux etc but I have a Windows
operating system 😒😕

**Comment by vmichalowski** [comment]
Hi @Shirlett 

Very nice work on your assignment! I also have a windows OS and have run into some trouble using make because of that :/

I just have a few comments for you:

- for your make file, I noticed that you had Rscript -e 'rmarkdown::render() at each step, to publish an md for each step - this is different from what I tried, which was to have Rscript -e 'rmarkdown::render() only at the last step, which publish a final report based on the previous steps. I think what you did (having a separate report for each step) works too though in terms of automation, since it looks like each step still builds on the last.
- I like how you included a brief description of what each function does -- I'm sure that will be a nice reference for you down the road too.
-  I also really like the data set you chose, and found the plots really interesting to see how different countries use internet! I didn't know about the subtitle or caption specifications in ggplot, or about how to make a choropleth map, but they look really great, and definitely things I want to use in the future.
- your statistical analyses were very well done as well - the only thing was that when the figures are arranged in a grid at the end, they turn out quite small and hard to read, but this may depend on how they are published.
- for your step 3, the only thing that I'm not sure about is your ordering of significance values - were these p-values? If so, it doesn't look like they are significant by traditional cut-off points, and I'm not sure if it would be correct to order by significance value in any case - it would probably be more informative to see something like effect sizes, but I'm not really sure how to get that out of R yet anyways, so I can see why you would go for that.

Overall, great work!

Victoria
